name: Java CI with Maven

on:
  push:
    paths:
      - 'project-12-stopwatch/**'
  pull_request:
    paths:
      - 'project-12-stopwatch/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-12-stopwatch

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install
